version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: better-sqlite3
    versions:
    - 7.1.4
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: whatsapp-web.js
    versions:
    - 1.12.1
    - 1.12.2
    - 1.12.3
    - 1.12.4
    - 1.12.5
  - dependency-name: enmap
    versions:
    - 5.8.4
